import { ObjectPropByName } from '@/types/Generics';
import { Stack } from '@mui/material';
import { FunctionComponent } from 'react';
import {
  BiBookAdd,
  BiBot,
  BiBowlHot,
  BiBrain,
  BiCctv,
  BiChalkboard,
  BiCheese,
  BiCloset,
  BiCookie,
  BiCut,
  BiPen,
  BiPencil,
  BiRun,
} from 'react-icons/bi';
import { BsGenderTrans } from 'react-icons/bs';
import {
  IoAccessibilityOutline,
  IoAirplaneOutline,
  IoAlarmOutline,
  IoAmericanFootballOutline,
  IoApertureOutline,
  IoAt,
  IoAttach,
  IoBalloonOutline,
  IoBandageOutline,
  IoBarbellOutline,
  IoBarChart,
  IoBaseballOutline,
  IoBasketballOutline,
  IoBicycleOutline,
  IoBoatOutline,
  IoBowlingBallOutline,
  IoBriefcaseOutline,
  IoBrushOutline,
  IoBugSharp,
  IoBuildOutline,
  IoBulbOutline,
  IoBusinessOutline,
  IoBusOutline,
  IoCafeOutline,
  IoCalculatorSharp,
  IoCalendarOutline,
  IoCameraOutline,
  IoCartOutline,
  IoChatbubblesOutline,
  IoCloudOutline,
  IoCodeSlashOutline,
  IoCogSharp,
  IoColorPaletteOutline,
  IoCompassOutline,
  IoDesktopOutline,
  IoDiamondOutline,
  IoEarth,
  IoExtensionPuzzleOutline,
  IoFemaleOutline,
  IoFilmOutline,
  IoFingerPrintOutline,
  IoFishOutline,
  IoFlashOutline,
  IoFootballOutline,
  IoFootstepsOutline,
  IoGameControllerOutline,
  IoGlassesOutline,
  IoHammerOutline,
  IoHandLeftOutline,
  IoHourglassOutline,
  IoIceCreamOutline,
  IoInformationCircleOutline,
  IoKeyOutline,
  IoLanguageOutline,
  IoLeafOutline,
  IoMagnetOutline,
  IoMaleOutline,
  IoMicOutline,
  IoMusicalNotesOutline,
  IoPlanetOutline,
  IoRestaurantOutline,
  IoRocketOutline,
  IoSchoolOutline,
  IoSearch,
  IoSubwayOutline,
  IoSunnyOutline,
  IoTelescope,
  IoTrophyOutline,
  IoUmbrellaOutline,
  IoVideocamOutline,
  IoVolumeMediumOutline,
  IoWalk,
} from 'react-icons/io5';
import {
  LiaAccessibleIcon,
  LiaAddressCard,
  LiaAnchorSolid,
  LiaAngry,
  LiaAnkhSolid,
  LiaAppleAltSolid,
  LiaAtomSolid,
  LiaAwardSolid,
  LiaBabyCarriageSolid,
  LiaBalanceScaleSolid,
  LiaBinocularsSolid,
  LiaBirthdayCakeSolid,
  LiaBroomSolid,
  LiaBullseyeSolid,
  LiaCarrotSolid,
  LiaCarSideSolid,
  LiaChessKnightSolid,
  LiaCrossSolid,
  LiaCrownSolid,
  LiaCrowSolid,
  LiaDiceD6Solid,
  LiaDrumSolid,
  LiaFlag,
  LiaFlaskSolid,
  LiaFly,
  LiaGuitarSolid,
  LiaHandshake,
  LiaHorseSolid,
  LiaPiggyBankSolid,
  LiaTshirtSolid,
} from 'react-icons/lia';
/**
 * How to use:
 * 1. Import all required MUI or other SVG icons into this file.
 * 2. Add icons with "unique lowercase names" into ICONS object.
 * 3. Use icons everywhere in the App by their names in <AppIcon icon="xxx" /> component
 * Important: properties of ICONS object MUST be lowercase!
 * Note: You can use camelCase or UPPERCASE in the <AppIcon icon="someIconByName" /> component
 */
export const CAT_ICONS = {
  accessibility: IoAccessibilityOutline,
  addressCard: LiaAddressCard,
  airplane: IoAirplaneOutline,
  alarm: IoAlarmOutline,
  americanFootball: IoAmericanFootballOutline,
  anchor: LiaAnchorSolid,
  angry: LiaAngry,
  ankh: LiaAnkhSolid,
  aperture: IoApertureOutline,
  apple: LiaAppleAltSolid,
  at: IoAt,
  atom: LiaAtomSolid,
  attach: IoAttach,
  award: LiaAwardSolid,
  baby: LiaBabyCarriageSolid,
  balance: LiaBalanceScaleSolid,
  balloon: LiaFly,
  bandage: IoBandageOutline,
  barChart: IoBarChart,
  barbell: IoBarbellOutline,
  baseball: IoBaseballOutline,
  basketball: IoBasketballOutline,
  beaker: LiaFlaskSolid,
  bicycle: IoBicycleOutline,
  binocular: LiaBinocularsSolid,
  bird: LiaCrowSolid,
  birthday: LiaBirthdayCakeSolid,
  boat: IoBoatOutline,
  bolt: IoFlashOutline,
  book: BiBookAdd,
  bot: BiBot,
  bowl: BiBowlHot,
  bowling: IoBowlingBallOutline,
  brain: BiBrain,
  briefcase: IoBriefcaseOutline,
  broom: LiaBroomSolid,
  brush: IoBrushOutline,
  bug: IoBugSharp,
  build: IoBuildOutline,
  bulb: IoBulbOutline,
  bullseye: LiaBullseyeSolid,
  bus: IoBusOutline,
  building: IoBusinessOutline,
  cafe: IoCafeOutline,
  calculator: IoCalculatorSharp,
  calendar: IoCalendarOutline,
  camera: IoCameraOutline,
  car: LiaCarSideSolid,
  carrot: LiaCarrotSolid,
  cart: IoCartOutline,
  cctv: BiCctv,
  chalkboard: BiChalkboard,
  chat: IoChatbubblesOutline,
  cheese: BiCheese,
  chess: LiaChessKnightSolid,
  closet: BiCloset,
  cloud: IoCloudOutline,
  code: IoCodeSlashOutline,
  cog: IoCogSharp,
  color: IoColorPaletteOutline,
  compass: IoCompassOutline,
  computer: IoDesktopOutline,
  cookie: BiCookie,
  cross: LiaCrossSolid,
  crown: LiaCrownSolid,
  cut: BiCut,
  diamond: IoDiamondOutline,
  dice: LiaDiceD6Solid,
  drum: LiaDrumSolid,
  earth: IoEarth,
  economy: LiaPiggyBankSolid,
  female: IoFemaleOutline,
  fingerprint: IoFingerPrintOutline,
  fish: IoFishOutline,
  film: IoFilmOutline,
  flag: LiaFlag,
  food: IoRestaurantOutline,
  football: IoFootballOutline,
  footsteps: IoFootstepsOutline,
  game: IoGameControllerOutline,
  glasses: IoGlassesOutline,
  graduation: IoSchoolOutline,
  guitar: LiaGuitarSolid,
  hammer: IoHammerOutline,
  hand: IoHandLeftOutline,
  handshake: LiaHandshake,
  horse: LiaHorseSolid,
  hourglass: IoHourglassOutline,
  iceCream: IoIceCreamOutline,
  info: IoInformationCircleOutline,
  key: IoKeyOutline,
  language: IoLanguageOutline,
  leaf: IoLeafOutline,
  magnet: IoMagnetOutline,
  male: IoMaleOutline,
  mic: IoMicOutline,
  music: IoMusicalNotesOutline,
  party: IoBalloonOutline,
  planet: IoPlanetOutline,
  pen: BiPen,
  pencil: BiPencil,
  puzzle: IoExtensionPuzzleOutline,
  rocket: IoRocketOutline,
  run: BiRun,
  umbrella: IoUmbrellaOutline,
  search: IoSearch,
  sound: IoVolumeMediumOutline,
  shirt: LiaTshirtSolid,
  sun: IoSunnyOutline,
  telescope: IoTelescope,
  train: IoSubwayOutline,
  transgender: BsGenderTrans,
  trophy: IoTrophyOutline,
  video: IoVideocamOutline,
  walk: IoWalk,
  wheelchair: LiaAccessibleIcon,
};

export type CategoryIconType = keyof typeof CAT_ICONS;

interface Props {
  icon: CategoryIconType; // Icon's name alternate prop
  size?: 'small' | 'medium' | 'large' | 'xl' | 'full'; // Icon's name alternate prop,
  sx?: ObjectPropByName;
}

/**
 * Renders SVG icon by given Icon name
 * @component AppIcon
 * @param {string} [props.name] - name of the Icon to render
 * @param {string} [props.icon] - name of the Icon to render
 */
const CategoryIcon: FunctionComponent<Props> = ({ icon, size = 'md', sx, ...restOfProps }) => {
  const ComponentToRender = CAT_ICONS[icon];
  const currentSize =
    size === 'small' ? '16px' : size === 'large' ? '32px' : size === 'xl' ? '40px' : size === 'full' ? '100%' : '24px'; // no size === md
  return (
    <Stack alignItems="center" justifyContent="center" sx={{ fontSize: currentSize, ...sx }}>
      <ComponentToRender {...restOfProps} />
    </Stack>
  );
};

export default CategoryIcon;
