services:
  frontend:
    image: aulaapp/aula-frontend:pr-${PR_NUMBER}
    container_name: aula-frontend_pr-${PR_NUMBER}
    env:
      - DOCKER_AULA_BASENAME='"${PR_NUMBER}"'
    networks:
      - aula_aula_external

networks:
  aula_aula_external:
    driver: bridge
    external: true
