import { Stack, StackProps } from '@mui/material';
import React from 'react';
import {
  BiAngry,
  BiArchiveIn,
  BiArchiveOut,
  BiBookAdd,
  BiBot,
  BiBowlHot,
  BiBrain,
  BiCctv,
  BiChalkboard,
  BiCheese,
  BiCloset,
  BiConfused,
  BiCookie,
  BiCool,
  BiCut,
  BiDizzy,
  BiHandicap,
  BiHappyAlt,
  BiHappyBeaming,
  BiLaugh,
  BiMehAlt,
  BiMehBlank,
  BiPen,
  BiPencil,
  BiRun,
  BiSad,
  BiShocked,
  BiSmile,
} from 'react-icons/bi';
import { BsGenderTrans, BsTree } from 'react-icons/bs';
import {
  HiHeart,
  HiLink,
  HiOutlineAcademicCap,
  HiOutlineArchiveBox,
  HiOutlineArrowDownOnSquare,
  HiOutlineArrowRightEndOnRectangle,
  HiOutlineBars3,
  HiOutlineBell,
  HiOutlineBugAnt,
  HiOutlineCamera,
  HiOutlineChartBar,
  HiOutlineChatBubbleLeft,
  HiOutlineChatBubbleLeftRight,
  HiOutlineChatBubbleOvalLeft,
  HiOutlineCheckBadge,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineClock,
  HiOutlineCog6Tooth,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentText,
  HiOutlineEllipsisHorizontal,
  HiOutlineEllipsisVertical,
  HiOutlineEnvelope,
  HiOutlineExclamationTriangle,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineFaceSmile,
  HiOutlineFlag,
  HiOutlineFunnel,
  HiOutlineHandThumbDown,
  HiOutlineHandThumbUp,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineInformationCircle,
  HiOutlineKey,
  HiOutlineLightBulb,
  HiOutlineLockClosed,
  HiOutlineLockOpen,
  HiOutlineMagnifyingGlass,
  HiOutlineMagnifyingGlassMinus,
  HiOutlineMagnifyingGlassPlus,
  HiOutlineMegaphone,
  HiOutlineMinusCircle,
  HiOutlineMoon,
  HiOutlinePencil,
  HiOutlinePlus,
  HiOutlinePrinter,
  HiOutlineQuestionMarkCircle,
  HiOutlineSun,
  HiOutlineTrash,
  HiOutlineUser,
  HiOutlineUserGroup,
  HiOutlineUserPlus,
  HiOutlineUsers,
  HiOutlineXCircle,
  HiOutlineXMark,
  HiQuestionMarkCircle,
  HiTag,
} from 'react-icons/hi2';
import {
  IoAccessibilityOutline,
  IoAirplaneOutline,
  IoAlarmOutline,
  IoAmericanFootballOutline,
  IoApertureOutline,
  IoAt,
  IoAttach,
  IoBalloonOutline,
  IoBandageOutline,
  IoBarbellOutline,
  IoBarChart,
  IoBaseballOutline,
  IoBasketballOutline,
  IoBicycleOutline,
  IoBoatOutline,
  IoBowlingBallOutline,
  IoBriefcaseOutline,
  IoBrushOutline,
  IoBugOutline,
  IoBuildOutline,
  IoBulbOutline,
  IoBusinessOutline,
  IoBusOutline,
  IoCafeOutline,
  IoCalculatorSharp,
  IoCalendarOutline,
  IoCameraOutline,
  IoCartOutline,
  IoChatbubblesOutline,
  IoCloudOutline,
  IoCodeSlashOutline,
  IoCogSharp,
  IoColorPaletteOutline,
  IoCompassOutline,
  IoDesktopOutline,
  IoDiamondOutline,
  IoEarth,
  IoExtensionPuzzleOutline,
  IoFemaleOutline,
  IoFilmOutline,
  IoFingerPrintOutline,
  IoFishOutline,
  IoFlashOutline,
  IoFlowerOutline,
  IoFootballOutline,
  IoFootstepsOutline,
  IoGameControllerOutline,
  IoGlassesOutline,
  IoHammerOutline,
  IoHandLeftOutline,
  IoHourglassOutline,
  IoIceCreamOutline,
  IoInformationCircleOutline,
  IoKeyOutline,
  IoLanguageOutline,
  IoLeafOutline,
  IoMagnetOutline,
  IoMaleOutline,
  IoMicOutline,
  IoMusicalNotesOutline,
  IoPlanetOutline,
  IoRestaurantOutline,
  IoRocketOutline,
  IoSchoolOutline,
  IoSearch,
  IoSubwayOutline,
  IoSunnyOutline,
  IoTelescope,
  IoTrophyOutline,
  IoUmbrellaOutline,
  IoVideocamOutline,
  IoVolumeMediumOutline,
  IoWalk,
} from 'react-icons/io5';
import {
  LiaAccessibleIcon,
  LiaAddressCard,
  LiaAnchorSolid,
  LiaAnkhSolid,
  LiaAppleAltSolid,
  LiaAtomSolid,
  LiaAwardSolid,
  LiaBabyCarriageSolid,
  LiaBalanceScaleSolid,
  LiaBinocularsSolid,
  LiaBirthdayCakeSolid,
  LiaBroomSolid,
  LiaBullseyeSolid,
  LiaCarrotSolid,
  LiaCarSideSolid,
  LiaChessKnightSolid,
  LiaCrossSolid,
  LiaCrownSolid,
  LiaCrowSolid,
  LiaDiceD6Solid,
  LiaDrumSolid,
  LiaFlag,
  LiaFlaskSolid,
  LiaFly,
  LiaGuitarSolid,
  LiaHandshake,
  LiaHorseSolid,
  LiaPiggyBankSolid,
  LiaTshirtSolid,
} from 'react-icons/lia';
import { LuSigma } from 'react-icons/lu';
import { PiCookingPotLight } from 'react-icons/pi';
import CircleIcon from './circle.svg?react';
import VotingIcon from './voting.svg?react';

/**
 * How to use:
 * 1. Import all required MUI or other SVG icons into this file.
 * 2. Add icons with "unique lowercase names" into ICONS object.
 * 3. Use icons everywhere in the App by their names in <AppIcon icon="xxx" /> component
 * Important: properties of ICONS object MUST be lowercase!
 * Note: You can use camelCase or UPPERCASE in the <AppIcon icon="someIconByName" /> component
 */
export const ICONS = {
  abstention: CircleIcon,
  account: HiOutlineFaceSmile,
  add: HiOutlinePlus,
  against: HiOutlineXCircle,
  alert: HiOutlineExclamationTriangle,
  announcement: HiOutlineMegaphone,
  announcements: HiOutlineMegaphone,
  archive: BiArchiveIn,
  arrowup: HiOutlineChevronUp,
  arrowdown: HiOutlineChevronDown,
  arrowright: HiOutlineChevronRight,
  arrowleft: HiOutlineChevronLeft,
  approval: HiOutlineQuestionMarkCircle,
  approved: HiOutlineHandThumbUp,
  avatar: HiOutlineFaceSmile,
  back: HiOutlineChevronLeft,
  bell: HiOutlineBell,
  box: HiOutlineArchiveBox,
  bug: HiOutlineBugAnt,
  camera: HiOutlineCamera,
  cancel: HiOutlineXCircle,
  categories: HiTag,
  chart: HiOutlineChartBar,
  chat: HiOutlineChatBubbleLeft,
  check: HiOutlineCheckCircle,
  close: HiOutlineXMark,
  clock: HiOutlineClock,
  comment: HiOutlineChatBubbleOvalLeft,
  copy: HiOutlineDocumentDuplicate,
  day: HiOutlineSun,
  delete: HiOutlineTrash,
  delegate: HiOutlineUsers,
  discussion: HiOutlineChatBubbleLeftRight,
  download: HiOutlineArrowDownOnSquare,
  edit: HiOutlinePencil,
  ellipsis: HiOutlineEllipsisHorizontal,
  filter: HiOutlineFunnel,
  for: HiOutlineCheckCircle,
  forbid: HiOutlineMinusCircle,
  group: HiOutlineUsers,
  heart: HiOutlineHeart,
  heartFull: HiHeart,
  help: HiQuestionMarkCircle,
  home: HiOutlineHome,
  idea: HiOutlineLightBulb,
  info: HiOutlineInformationCircle,
  key: HiOutlineKey,
  link: HiLink,
  lockOpen: HiOutlineLockOpen,
  lockClosed: HiOutlineLockClosed,
  login: HiOutlineUser,
  logout: HiOutlineArrowRightEndOnRectangle,
  menu: HiOutlineBars3,
  more: HiOutlineEllipsisVertical,
  message: HiOutlineEnvelope,
  messages: HiOutlineEnvelope,
  neutral: HiOutlineMinusCircle,
  night: HiOutlineMoon,
  notifications: HiOutlineBell,
  print: HiOutlinePrinter,
  results: HiOutlineChartBar,
  rejected: HiOutlineHandThumbDown,
  report: HiOutlineFlag,
  reports: HiOutlineFlag,
  request: HiOutlineExclamationTriangle,
  requests: HiOutlineExclamationTriangle,
  room: HiOutlineAcademicCap,
  search: HiOutlineMagnifyingGlass,
  settings: HiOutlineCog6Tooth,
  signup: HiOutlineUserPlus,
  survey: HiOutlineQuestionMarkCircle,
  text: HiOutlineDocumentText,
  unarchive: BiArchiveOut,
  users: HiOutlineUserGroup,
  visibilityOff: HiOutlineEye,
  visibilityOn: HiOutlineEyeSlash,
  voting: VotingIcon,
  waiting: HiOutlineQuestionMarkCircle,
  winner: HiOutlineCheckBadge,
  wild: HiOutlineLightBulb,
  zoomIn: HiOutlineMagnifyingGlassPlus,
  zoomOut: HiOutlineMagnifyingGlassMinus,
};

export const CAT_ICONS = {
  accessibility: IoAccessibilityOutline,
  addressCard: LiaAddressCard,
  airplane: IoAirplaneOutline,
  alarm: IoAlarmOutline,
  americanFootball: IoAmericanFootballOutline,
  anchor: LiaAnchorSolid,
  ankh: LiaAnkhSolid,
  aperture: IoApertureOutline,
  apple: LiaAppleAltSolid,
  at: IoAt,
  atom: LiaAtomSolid,
  attach: IoAttach,
  award: LiaAwardSolid,
  baby: LiaBabyCarriageSolid,
  balance: LiaBalanceScaleSolid,
  balloon: LiaFly,
  bandage: IoBandageOutline,
  barChart: IoBarChart,
  barbell: IoBarbellOutline,
  baseball: IoBaseballOutline,
  basketball: IoBasketballOutline,
  beaker: LiaFlaskSolid,
  bicycle: IoBicycleOutline,
  binocular: LiaBinocularsSolid,
  bird: LiaCrowSolid,
  birthday: LiaBirthdayCakeSolid,
  boat: IoBoatOutline,
  bolt: IoFlashOutline,
  book: BiBookAdd,
  bot: BiBot,
  bowl: BiBowlHot,
  bowling: IoBowlingBallOutline,
  brain: BiBrain,
  briefcase: IoBriefcaseOutline,
  broom: LiaBroomSolid,
  brush: IoBrushOutline,
  bug: IoBugOutline,
  bugs: IoBugOutline,
  build: IoBuildOutline,
  bulb: IoBulbOutline,
  bullseye: LiaBullseyeSolid,
  bus: IoBusOutline,
  building: IoBusinessOutline,
  cafe: IoCafeOutline,
  calculator: IoCalculatorSharp,
  calendar: IoCalendarOutline,
  camera: IoCameraOutline,
  car: LiaCarSideSolid,
  carrot: LiaCarrotSolid,
  cart: IoCartOutline,
  cctv: BiCctv,
  chalkboard: BiChalkboard,
  chat: IoChatbubblesOutline,
  cheese: BiCheese,
  chess: LiaChessKnightSolid,
  closet: BiCloset,
  cloud: IoCloudOutline,
  code: IoCodeSlashOutline,
  cog: IoCogSharp,
  color: IoColorPaletteOutline,
  compass: IoCompassOutline,
  computer: IoDesktopOutline,
  cookie: BiCookie,
  cross: LiaCrossSolid,
  crown: LiaCrownSolid,
  cut: BiCut,
  diamond: IoDiamondOutline,
  dice: LiaDiceD6Solid,
  drum: LiaDrumSolid,
  earth: IoEarth,
  economy: LiaPiggyBankSolid,
  female: IoFemaleOutline,
  fingerprint: IoFingerPrintOutline,
  fish: IoFishOutline,
  film: IoFilmOutline,
  flag: LiaFlag,
  flower: IoFlowerOutline,
  food: IoRestaurantOutline,
  football: IoFootballOutline,
  footsteps: IoFootstepsOutline,
  game: IoGameControllerOutline,
  glasses: IoGlassesOutline,
  graduation: IoSchoolOutline,
  guitar: LiaGuitarSolid,
  hammer: IoHammerOutline,
  hand: IoHandLeftOutline,
  handshake: LiaHandshake,
  handycap: BiHandicap,
  horse: LiaHorseSolid,
  hourglass: IoHourglassOutline,
  iceCream: IoIceCreamOutline,
  info: IoInformationCircleOutline,
  key: IoKeyOutline,
  language: IoLanguageOutline,
  leaf: IoLeafOutline,
  magnet: IoMagnetOutline,
  male: IoMaleOutline,
  math: LuSigma,
  mic: IoMicOutline,
  music: IoMusicalNotesOutline,
  pan: PiCookingPotLight,
  party: IoBalloonOutline,
  planet: IoPlanetOutline,
  pen: BiPen,
  pencil: BiPencil,
  puzzle: IoExtensionPuzzleOutline,
  rocket: IoRocketOutline,
  run: BiRun,
  umbrella: IoUmbrellaOutline,
  search: IoSearch,
  sound: IoVolumeMediumOutline,
  shirt: LiaTshirtSolid,
  sun: IoSunnyOutline,
  telescope: IoTelescope,
  train: IoSubwayOutline,
  transgender: BsGenderTrans,
  tree: BsTree,
  trophy: IoTrophyOutline,
  video: IoVideocamOutline,
  walk: IoWalk,
  wheelchair: LiaAccessibleIcon,
  angry: BiAngry,
  beaming: BiHappyBeaming,
  blank: BiMehBlank,
  confused: BiConfused,
  cool: BiCool,
  dizzy: BiDizzy,
  happy: BiHappyAlt,
  laugh: BiLaugh,
  meh: BiMehAlt,
  sad: BiSad,
  shocked: BiShocked,
  smile: BiSmile,
};

const ALL_ICONS = { ...ICONS, ...CAT_ICONS };

export type IconType = keyof typeof ICONS;
export type CategoryIconType = keyof typeof CAT_ICONS;
export type AllIconsType = keyof typeof ALL_ICONS;

interface Props extends StackProps {
  icon: AllIconsType; // Icon's name alternate prop
  size?: 'xs' | 'small' | 'medium' | 'large' | 'xl' | 'xxl'; // Icon's name alternate prop,
}

/**
 * Renders SVG icon by given Icon name
 * @component AppIcon
 */
const AppIcon: React.FC<Props> = ({ icon, size = 'medium', sx, ...restOfProps }) => {
  const currentSize =
    size === 'xs'
      ? '16px'
      : size === 'small'
        ? '18px'
        : size === 'large'
          ? '32px'
          : size === 'xl'
            ? '40px'
            : size === 'xxl'
              ? '80px'
              : '24px'; // no size === md
  return (
    <Stack
      alignItems="center"
      justifyContent="center"
      sx={{
        fontSize: currentSize,
        minWidth: currentSize,
        width: currentSize,
        height: currentSize,
        ...sx,
      }}
      {...restOfProps}
    >
      {icon in ALL_ICONS ? React.createElement(ALL_ICONS[icon]) : <></>}
    </Stack>
  );
};

export default AppIcon;
