name: Update development environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: false
      LOCAL: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build frontend
        run: |
          npm i
          npm run build-devel
          cp -vr build/* /var/www/
          # git checkout test
          # npm run build
          # cp -vr build/* /var/www-test/
        shell: bash
