name: E2E Tests

on:
  # schedule:
  #   - cron: "15 5 * * *"
  workflow_dispatch:
  # WARN: Remove when ready `pull_request_target` is bad juju
  pull_request_target:
    types: [opened, synchronize]

env:
  AULA_HOST: host.docker.internal
  AULA_PORT: '8000'

jobs:
  run-aula:
    runs-on: [self-hosted, cicd]
    env:
      COMPOSE_NAME: aula-e2e-${{ github.sha }}
      IMAGE_NAME: aula-ansible-${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create roles folder
        run: |
          mkdir -p ./roles

      - name: Checkout aula role
        uses: actions/checkout@v6
        with:
          repository: aula-app/ansible-role-aula
          ssh-key: '${{ secrets.ANSIBLE_DEPLOY_KEY }}'
          path: ./roles/ansible-role-aula

      - name: Setup docker builder
        uses: docker/setup-buildx-action@v3

      - name: Build ansible container image
        run: |
          docker build -f ./roles/ansible-role-aula/.docker/Dockerfile -t ${{ env.IMAGE_NAME }}:latest ./roles/ansible-role-aula/

      - name: Create Ansible playbook
        run: |
          cat <<- 'EOF' > playbook.yml
          - name: Install aula backend locally for E2E testing
            hosts: localhost
            become_method: su
            become_user: root
            roles:
              - aula
          EOF

      - name: Create inventory file
        run: |
          cat <<- 'EOF' > inventory.yml
          ---
          all:
            hosts:
              localhost:
                ansible_connection: local
                ansible_python_interpreter: /usr/local/bin/python3
                ansible_user: ansible
                apache2_user: www
                network:
                  ssl_enabled: false
                  base_domain: "${{ env.AULA_HOST }}"
                  httpPort: "${{ env. AULA_PORT }}"
                email:
                  backend: log
                aula:
                  compose_name: ${{ env.COMPOSE_NAME }}
                  environment: dev
                  base_url: "http://${{ env.AULA_HOST }}:${{ env. AULA_PORT }}"
                  superkey: "hunter2"
                  is_pr_deployment_enabled: false
                  multi_instance_enabled: false
                  db:
                    name: "aula_dbname"
                    user: "aula_user"
                    pass: "hunter2"
                    root_password: "hunter2"
                  email:
                    from: admin@aula.local
                    support: support@aula.local
                  manager:
                    db:
                      name: "aula_manager"
                      user: "aula_manager_user"
                      pass: "hunter2"
                  backup:
                    enabled: false
                auth0:
                  domain: "AUTH0-DOMAIN"
                  client_id: "AUTH0-CLIENT-ID"
                  client_secret: auth0-secret
                  cookie_secret: hunter2
                  redirect_uri: "http://${{ env.AULA_HOST }}:${{ env. AULA_PORT }}/api/controllers/auth0.php"
                  frontend_redirect: "http://${{ env.AULA_HOST }}:${{ env. AULA_PORT }}/oauth-login/"
          EOF

      - name: Run ansible
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /opt/aula:/opt/aula \
            -v "$(pwd)/playbook.yml":/usr/local/share/aula/ansible/playbook.yml \
            -v "$(pwd)/inventory.yml":/usr/local/share/aula/ansible/inventory.yml \
            ${{ env.IMAGE_NAME }}:latest ansible-playbook playbook.yml -i inventory.yml

  e2e-tests:
    runs-on: [self-hosted, cicd]
    continue-on-error: true # allow failing e2e tests while testing
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy
    steps:
      - name: Install Playwright
        run: npx playwright install

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        env:
          APP_FRONTEND_HOST: http://${{ env.AULA_HOST }}:${{ env. AULA_PORT }}
          APP_BACKEND_HOST: http://${{ env.AULA_HOST }}:${{ env. AULA_PORT }}
        run: yarn test

  cleanup:
    runs-on: [self-hosted, cicd]
    steps:
      - name: Cleanup running services and files
        if: ${{ always() }}
        run: |
          for name in $(docker ps --format '{{ .Names }}'); do
            if [[ "$name" == ${{ env.COMPOSE_NAME }}* ]]; then
              echo "Removing: $name"
              docker rm -f "$name"
            fi
          done
          docker ps -a
