name: Feature Branch Deployment

on:
  push:
    branches:
      - 'feature-**'
      - 'feat-**'
      - 'feature/**'
      - 'feat/**'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '22'
  DEPLOY_BASE_PATH: '/var/www-branch'

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Get branch name
        id: branch-name
        run: |
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
          # Convert branch name to URL-safe format
          SAFE_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/-/g')
          echo "SAFE_BRANCH_NAME=$SAFE_BRANCH_NAME" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build
        env:
          # Add any environment variables needed for your build
          PUBLIC_URL: /${{ env.SAFE_BRANCH_NAME }}

      - name: Deploy to Apache directory
        run: |
          DEPLOY_PATH="${{ env.DEPLOY_BASE_PATH }}/${{ env.SAFE_BRANCH_NAME }}"
          
          # Create the directory if it doesn't exist
          sudo mkdir -p $DEPLOY_PATH
          
          # Copy the built files
          sudo rm -rf $DEPLOY_PATH/*
          sudo cp -r ./build/* $DEPLOY_PATH/
          
          # Ensure proper permissions
          sudo chown -R www-data:www-data $DEPLOY_PATH
          sudo chmod -R 755 $DEPLOY_PATH

          # - name: Comment on PR
          #   if: github.event_name == 'pull_request'
          #   uses: actions/github-script@v7
          #   with:
          #     script: |
          #       const branch = process.env.SAFE_BRANCH_NAME;
          #       const baseUrl = process.env.SITE_BASE_URL || `http://${process.env.HOSTNAME}`;
          #       const deployUrl = `${baseUrl}/previews/${branch}/`;
          #       
          #       github.rest.issues.createComment({
          #         issue_number: context.issue.number,
          #         owner: context.repo.owner,
          #         repo: context.repo.name,
          #         body: `✨ Preview deployment is ready!\n\nYou can view this branch at: ${deployUrl}`
          #       })
          #   env:
          #     SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }}
