name: Update staging instance

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: false
      LOCAL: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build frontend
        run: |
          npm i
          npm run build-staging
          cp -vr build/* /var/www-aula-staging/
        shell: bash
